apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonebook 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phonebook
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: phonebook
      annotations:
        prometheus.io/probe: 'true'
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: phonebook
        image: "daximillian/myphonebook"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi
        env:
        - name: PB_USER
          valueFrom:
            secretKeyRef: boring-data
              key: username
        - name: PB_PASS
          valueFrom:
            secretKeyRef: boring-data
              key: password
        - name: PB_HOST
          value: "mysql.service.consul"
        - name: PB_DB
          value: "phonebook"
        - name: PB_PORT
          value: "3306"
        - name: PB_LOG
          value: "info"
        ports:
        - containerPort: 8000     
        imagePullPolicy: Always
