apiVersion: v1
kind: Service
metadata:
  name: phonebook-lb
  annotations:
    prometheus.io/probe: 'true' 
    prometheus.io/scrape: 'true'
  labels:
    app: phonebook
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: phonebook
  type: LoadBalancer