apiVersion: v1
kind: Service
metadata:  
  name: phonebook-service
spec:
  selector:    
    app: phonebook
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30039
    protocol: TCP