apiVersion: v1
kind: Service
metadata:  
  name: phonebook-service
  annotations:
    prometheus.io/probe: 'true' 
    prometheus.io/scrape: 'true'
spec:
  selector:    
    app: phonebook
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 8000
    nodePort: 30039
    protocol: TCP
  - name: mysql
    port: 3306
    targetPort: 3306
    nodePort: 30040
    protocol: TCP